version: "3"
services:
  db:
    image: mysql:latest
    hostname: db 
    container_name: db 
    volumes:
        - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./mysql-conf:/etc/mysql/conf.d
        - ./mysql:/var/lib/mysql
    environment:    
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=teste
        - MYSQL_USER=teste
        - MYSQL_PASSWORD=teste
    ports:
        - "3306:3306"
        - "33060:33060"

  app:
    image: php:7.4-cli 
    container_name: app
    working_dir: /app
    volumes:
      - ./app/:/app
    command: php -S 0.0.0.0:8080 /app/index.php   
    depends_on:
      - db 
    ports:
        - "8080:8080"
